#!/usr/bin/env bash
# Print domains and subdomains

print_domain_subdomain () {
    local domain="$1"
    local subdomain="$2"
    local result=$(dig "$domain" +short | grep -A1 'ANSWER SECTION:')

    if [ -n "$result" ]; then
        local formatted_result=$(echo "$result" | sed -r "s/$domain/$subdomain/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }')
        echo "$formatted_result"
    else
        echo "Error: Unable to retrieve information for $subdomain.$domain"
    fi
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
else
    print_domain_subdomain "$1" "www"
    print_domain_subdomain "$1" "lb-01"
    print_domain_subdomain "$1" "web-01"
    print_domain_subdomain "$1" "web-02"
fi
