#!/usr/bin/env bash
# This script installs nginx on Ubuntu server and configures redirection

# Install nginx
sudo apt-get install -y nginx

# Allow incoming connections on port 80 using UFW
sudo ufw allow 'Nginx HTTP'

# Create a simple "Hello World!" page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Define the redirection location
redirect_location="http://pronic.tech"

# Add the redirection rule to Nginx configuration
line="\\\trewrite ^/redirect_me $redirect_location permanent;"
sudo sed -i "/server_name _;/a $line" /etc/nginx/sites-available/default

# Check Nginx configuration syntax
sudo nginx -t

# Restart Nginx
sudo service nginx restart

# Output success message
echo "Nginx configured for redirection successfully."
