#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#    Listens on port 80.
#    Returns a page containing "Hello World!" when queried
#    at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /etc/nginx/html
sudo tee /etc/nginx/html/index.html > /dev/null <<EOF
Hello World!
EOF

sudo tee /etc/nginx/html/404.html > /dev/null <<EOF
Ceci n'est pas une page
EOF

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By \$hostname;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}
EOF

sudo service nginx restart
