#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#    Enables management via the init script.
#    Distributes requests using a round-robin algorithm.

# Update and upgrade
sudo apt-get -y update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy management via init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Backup the original haproxy.cfg
sudo mv /etc/haproxy/haproxy.cfg{,.original}

# Configure haproxy.cfg using tee
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 3.84.239.19:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 83865-web-01 52.86.71.142 check
    server 83865-web-02 34.203.201.129 check
EOF

# Start HAProxy service
sudo service haproxy start

# Exit script
exit 0
