#!/usr/bin/env bash

script_path="/path/to/manage_my_process"
pid_file="/var/run/my_process.pid"

case "$1" in
    start)
        if [ -f $pid_file ]; then
            echo "manage_my_process is already running. Check $pid_file for PID."
            exit 1
        fi
        $script_path &
        echo $! > $pid_file
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f $pid_file ]; then
            pid=$(cat $pid_file)
            kill $pid
            rm $pid_file
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        $0 stop
        sleep 2
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
