#!/usr/bin/env bash

# Function to handle SIGTERM signal
function handle_sigterm {
    echo "I am invincible!!!"
    exit
}

# Trap SIGTERM and associate it with the handle_sigterm function
trap 'handle_sigterm' SIGTERM

# Infinite loop with a sleep of 2 seconds between each iteration
while true; do
    echo "To infinity and beyond"
    sleep 2
done
