#!/usr/bin/env bash
# This script tells the story of each user in /etc/passwd

while IFS=: read -r username password uid gid info home_dir shell
do
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
