#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data with the occurrence number

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'
