#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration, it says "Hi" on a new line

counter=0

while [ $counter -lt 10 ]
do
    if [ $counter -eq 8 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
