#!/usr/bin/env bash
# script that configures an Ubuntu server as follows:
# **** localhost resolves to 127.0.0.2
# **** facebook.com resolves to 8.8.8.8

# Copy the original hosts file to a new file in the home directory
cp /etc/hosts ~/hosts.new

# Update the new hosts file: Set localhost to resolve to 127.0.0.2
echo "127.0.0.2    localhost" > ~/hosts.new

# Append a line to the new hosts file: Set facebook.com to resolve to 8.8.8.8
echo "8.8.8.8      facebook.com" >> ~/hosts.new

# Overwrite the original hosts file with the modified one
cp -f ~/hosts.new /etc/hosts
