#!/usr/bin/env bash

# Ensure the SSH configuration file exists
touch ~/.ssh/config

# Set the required options in the SSH configuration file
echo "PasswordAuthentication no" >> ~/.ssh/config
echo "IdentityFile ~/.ssh/school" >> ~/.ssh/config
